version: '3'
services:
    mongo:
        build: ./mongo
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - $HOME/Mongo/Dota:/data/db
        command: mongod
    spark-base:
        build:
            context: ./spark-base
            args:
                - GlibcVersion=2.25-r0
                - SparkVersion=2.1.1
                - HadoopVersion=2.7
                - JavaVersion=8
                - JavaUpdate=131
                - JavaBuild=11
                - JavaSig=d54c1d3a095b4ff2b6607d096fa80163
        image: spark-base
    spark-master:
        build: ./spark-master
        image: spark-master
        container_name: master
        hostname: master
        depends_on:
            - spark-base
            - mongo
        ports:
            - "8080:8080"
            - "7077:7077"
        command: ./bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        #/usr/bin/supervisord --configuration=/master.conf
    spark-slave:
        build: ./spark-slave
        image: spark-slave
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        command: /usr/bin/supervisord --configuration=/slave.conf
