version: '3.3'
services:
    mongo:
        build: ../mongodb
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - $HOME/Mongo/Dota:/data/db
        command: mongod
    spark-master:
        build: .
        image: spark-master
        container_name: master
        hostname: master
        depends_on:
            - mongo
        ports:
            - "8080:8080"
            - "7077:7077"
        command: ./bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    spark-slave:
        build: .
        image: spark-slave
        depends_on:
            - spark-master
#        ports for worker web ui
#        ports:
#            - "8081:8081"
        command: ./bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
